# version: '2.25'
services:
  app:
    image: username/backend:latest # Replace with your actual Spring Boot Docker image tag
    ports:
      - "8080:8080"
    container_name: backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bank?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: SSAFY
      TZ: Asia/Seoul
      # Add other environment variables here ss
    networks:
      - docker-network

  mysql:
    image: mysql:8.0.30 # Replace with your actual MySQL Docker image tag
    environment:
      MYSQL_ROOT_PASSWORD: SSAFY
      MYSQL_DATABASE: bank
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql
    command: --default-time-zone='+09:00'
    networks:
      - docker-network

  frontend:
    image: username/frontend:latest # Replace with your actual frontend Docker image tag
    ports:
      - "8081:80"
    networks:
      - docker-network
    depends_on:
      - app
    container_name: frontend
    environment:
      TZ: Asia/Seoul

networks:
  docker-network:
    external:
      name: docker-network
    driver: bridge
    labels:
      com.docker.compose.network: "true"

volumes:
  mysql-data:
    driver: local
