# version: '2.25'
services:
  app:
    image: ***REMOVED***/backend:latest # Replace with your actual Spring Boot Docker image tag
    ports:
      - "8080:8080"
    container_name: backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bank?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: SSAFY
      # Add other environment variables here
    networks:
      - app-network

  mysql:
    image: ***REMOVED***/mysql:latest # Replace with your actual MySQL Docker image tag
    environment:
      MYSQL_ROOT_PASSWORD: SSAFY
      MYSQL_DATABASE: bank
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql
    networks:
      - app-network

  frontend:
    image: ***REMOVED***/frontend:latest # Replace with your actual frontend Docker image tag
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - app
    container_name: frontend

networks:
  docker-network:
    external:
      name: docker-network
    driver: bridge
    labels:
      com.docker.compose.network: "true"

volumes:
  mysql-data:
    driver: local
